export enum ResourceEnum {
  CATEGORIE_PROFESSIONNELLE = "CATEGORIE_PROFESSIONNELLE",
  INSCRIPTION = "INSCRIPTION",
  OUVRIER = "OUVRIER",
  PAYS = "PAYS",
  PERMISSION = "PERMISSION",
  PRESTATION = "PRESTATION",
  PROFESSION = "PROFESSION",
  USER = "USER"
}
